//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mwf_designer
{
    
    #region Windows Form Designer generated code
    public partial class About
    {
        private void InitializeComponent()
        {
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            // 
            // groupBox1
            // 
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Credits";
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
                        | System.Windows.Forms.AnchorStyles.Right);
            this.groupBox1.Location = new System.Drawing.Point(194, 13);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(284, 131);
            this.groupBox1.TabIndex = 1;
            // 
            // About
            // 
            this.ClientSize = new System.Drawing.Size(494, 164);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "About";
            this.Controls.Add(this.groupBox1);
            this.Name = "About";
        }
        private System.Windows.Forms.GroupBox groupBox1;
    }
    #endregion
}
